<?php
/** @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<p><a href="<?= $escaper->escapeHtml($block->getUrl('oleksandrb_controllersdemo/foobar_yetanotherfolder/responseform', ['vendor_name' => 'Oleksandrb' , 'module_name' => 'ControllerDemos'])) ?>">ResponseForm</a></p>
<p><a href="<?= $escaper->escapeHtml($block->getUrl('oleksandrb_controllersdemo/foobar_yetanotherfolder/redirectresponsedemo')) ?>" target="_blank">RedirectResponseDemo</a></p>
<p><a href="<?= $escaper->escapeHtml($block->getUrl('oleksandrb_controllersdemo/foobar_yetanotherfolder/forwardresponsedemo', ['vendor_name' => 'Oleksandrb' , 'module_name' => 'ControllerDemos'])) ?>">ForwardResponseDemo</a></p>

<form method="get" action="<?= $escaper->escapeHtml($block->getUrl('oleksandrb_controllersdemo/foobar_yetanotherfolder/responseform')) ?>">
    <input type="text" name="vendor_name" value="Oleksandrb" style="width: 200px"><br><br>
    <input type="text" name="module_name" value="ControllerDemos" style="width: 200px"><br><br>
    <button type="submit"><?= $escaper->escapeHtml(__('Отправить')) ?></button>
</form>

